site_name: IoETPlanet
nav:
  - Home: index.md
  - Raspberry Pi:
      - Getting Started: raspberrypi/getting-started.md
      - Installing Docker on Raspberry Pi: raspberrypi/docker-on-raspberrypi.md
      - Projects:
          - Pico Project: raspberrypi/projects/Pico/index.md
          - Using GPS: raspberrypi/projects/GPS/getting-started.md
  - NVIDIA Jetson Nano:
     - Getting Started: nvidia/getting-started.md
     - Installing Docker on NVIDIA Jetson: nvidia/docker-on-jetson-nano.md
     - Projects:
          - BME Sensor Analytics using Redis TimeSeries, Grafana and Docker: nvidia/redis-grafana-docker.md
  - NVIDIA AGX Xavier:
     - Getting Started: nvidia/jetson-xavier.md
     - Installing Docker on NVIDIA Jetson Xavier: nvidia/docker-on-xavier.md

  - DJI Tello Drone:
     - Getting Started: tellodrone/getting-started.md
     - Using Python: tellodrone/python.md


theme: material
